-- local telescope = require("telescope")
-- local telescopeConfig = require("telescope.config")
-- local actions = require('telescope.actions')
--
-- -- Clone the default Telescope configuration
-- local vimgrep_arguments = { unpack(telescopeConfig.values.vimgrep_arguments) }
--
-- -- I want to search in hidden/dot files.
-- table.insert(vimgrep_arguments, "--hidden")
-- -- I don't want to search in the `.git` directory.
-- table.insert(vimgrep_arguments, "--glob")
-- table.insert(vimgrep_arguments, "!.git/*")
--
-- -- You dont need to set any of these options. These are the default ones. Only
-- -- the loading is important
-- telescope.setup {
--   defaults = {
--     mappings = {
--       i = {
--         ["<esc>"] = actions.close
--       },
--     },
--     -- `hidden = true` is not supported in text grep commands.
--     vimgrep_arguments = vimgrep_arguments,
--   },
--   extensions = {
--     fzf = {
--       fuzzy = true, -- false will only do exact matching
--       override_generic_sorter = true, -- override the generic sorter
--       override_file_sorter = true, -- override the file sorter
--       case_mode = "smart_case", -- or "ignore_case" or "respect_case"
--       -- the default case_mode is "smart_case"
--     }
--   },
--   pickers = {
--     find_files = {
--       -- `hidden = true` will still show the inside of `.git/` as it's not `.gitignore`d.
--       find_command = { "rg", "--files", "--hidden", "--glob", "!.git/*" },
--     },
--   },
-- }
-- -- To get fzf loaded and working with telescope, you need to call
-- -- load_extension, somewhere after setup function:
-- require('telescope').load_extension('fzf')
